multiservice deployment

diff --git a/.github/actions/deploy/compose/action.yml b/.github/actions/deploy/compose/action.yml
--- a/.github/actions/deploy/compose/action.yml
+++ b/.github/actions/deploy/compose/action.yml
@@ -27,21 +27,81 @@ inputs:
     required: false
     description: "delete folders before running 'docker compose up'"
 
-  domain_name:
-    required: true
-    description: 'domain name for project ${DOMAIN_NAME}.wlg.tv'
-  target_service:
+  target:
     required: false
-    description: 'service name of docker-compose.yml for proxy'
-  target_port:
+    description: 'provide target as: ${SUBDOMAIN_NAME}:${SERVICE_NAME}:${PORT}'
+  domain:
     required: false
-    description: 'service port of docker-compose.yml for proxy'
+    description: 'default: wlg.tv'
+    default: "wlg.tv"
 
 # ----------------------------------------------------------------------
 
 runs:
   using: composite
   steps:
+    - id: validate
+      name: validate input details before start
+      shell: bash
+      env:
+        BRANCH_NAME: ${{ github.ref_name }}
+      run: |
+        echo ""
+        echo "========== VALIDATE TARGETS =========="
+        echo ""
+
+        echo "${{ inputs.target }}" | tr -s '[:space:]' '\n' | while read -r target; do
+          # Skip empty lines
+          [[ -z "$target" ]] && continue
+
+          IFS=':' read -r DOMAIN_NAME SERVICE_NAME PORT <<< "$target"
+
+          # CHECK ALL NON EMPTY
+          if [[ -z "$DOMAIN_NAME" ]]; then
+            echo ::error::ERROR: subdomain name should be provided for "target" input
+            echo ::warning::expected input format: SUBDOMAIN:SERVICE:PORT
+            echo ::warning::domain will be appended as: ${DOMAIN}.${{ inputs.domain }}
+            exit 1
+          fi
+          if [[ -z "$SERVICE_NAME" ]]; then
+            echo ::error::ERROR: service name should be provided for "target" input
+            echo ::warning::expected input format: SUBDOMAIN:SERVICE:PORT
+            echo ::warning::SERVICE name is the name of service from docker-compose.yml
+            exit 1
+          fi
+          if [[ -z "$PORT" ]]; then
+            echo ::error::ERROR: port number should be provided for "target" input
+            echo ::warning::expected input format: SUBDOMAIN:SERVICE:PORT
+            exit 1
+          fi
+
+          # CHECK DOMAIN INPUT FORMAT (basic check: letters, numbers, dots, and dashes)
+          if ! [[ "$DOMAIN_NAME" =~ ^[a-zA-Z0-9.-]+$ ]]; then
+            echo "::error::ERROR: Invalid domain name format."
+            exit 1
+          fi
+          # CHECK SERVICE INPUT FORMAT (letters, numbers, dashes, underscores)
+          if ! [[ "$SERVICE_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
+            echo "::error::ERROR: Invalid service name format."
+            exit 1
+          fi
+          # CHECK PORT INPUT FORMAT (numeric and valid port range)
+          if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
+            echo "::error::ERROR: port must be numeric."
+            exit 1
+          elif (( PORT < 1 || PORT > 65535 )); then
+            echo "::error::ERROR: port must be between 1 and 65535."
+            exit 1
+          fi
+
+          # VALIDATE BRANCH NAME FOR TARGET DOMAIN NAME
+          if [ "${{ env.BRANCH_NAME }}" != "master" ]; then
+            DOMAIN_NAME=$DOMAIN_NAME.dev
+          fi
+          DOMAIN_NAME=$DOMAIN_NAME.${{ inputs.domain }}
+          echo "TARGET: $DOMAIN_NAME -> $SERVICE_NAME:$PORT"
+        done
+
     - id: ssh
       name: create ssh configuration
       shell: bash
@@ -69,36 +129,20 @@ runs:
       shell: bash
       env:
         REPOSITORY_NAME: ${{ github.event.repository.name }}
-        INPUT_DOMAIN_NAME: ${{ inputs.domain_name }}
-        INPUT_TARGET_HOST: ${{ inputs.target_service }}
-        INPUT_TARGET_PORT: ${{ inputs.target_port }}
         BRANCH_NAME: ${{ github.ref_name }}
       run: |
         echo ""
-        echo "========== SETUP NETWORK/DOMAIN NAMES =========="
+        echo "========== SETUP NETWORK =========="
         echo ""
         
         NETWORK_NAME=proxy-${{ env.REPOSITORY_NAME }}-network
-        DOMAIN_NAME=${{ env.INPUT_DOMAIN_NAME }}
-        TARGET_HOST=${{ env.INPUT_TARGET_HOST }}
-        TARGET_PORT=${{ env.INPUT_TARGET_PORT }}
-        
         if [ "${{ env.BRANCH_NAME }}" != "master" ]; then
           NETWORK_NAME=$NETWORK_NAME-dev
-          DOMAIN_NAME=$DOMAIN_NAME.dev
           echo "NETWORK NAME DEV = $NETWORK_NAME"
         fi
-        DOMAIN_NAME=$DOMAIN_NAME.wlg.tv
         
         echo "network=$NETWORK_NAME" >> $GITHUB_OUTPUT
-        echo "domain=$DOMAIN_NAME" >> $GITHUB_OUTPUT
-        echo "host=$TARGET_HOST" >> $GITHUB_OUTPUT
-        echo "port=$TARGET_PORT" >> $GITHUB_OUTPUT
-        
         echo "NETWORK NAME = $NETWORK_NAME"
-        echo "DOMAIN NAME  = $DOMAIN_NAME"
-        echo "TARGET HOST  = $TARGET_HOST"
-        echo "TARGET PORT  = $TARGET_PORT"
 
     - id: compose-remote
       name: create docker remote compose
@@ -139,11 +183,14 @@ runs:
     - id: compose-override
       name: create docker override compose
       shell: bash
+      env:
+        BRANCH_NAME: ${{ github.ref_name }}
       run: |
         echo ""
         echo "========== GENERATE DOCKER COMPOSE (OVERRIDE) =========="
         echo ""
-
+        
+        TARGETS=$(echo "${{ inputs.target }}" | tr -s '[:space:]' '\n')
         INPUT_FILE="docker-compose.yml"
         OUTPUT_FILE="docker-compose.override.yml"
         
@@ -166,28 +213,46 @@ runs:
         
           # Match lines indented exactly 2 spaces (first-level keys under services)
           if $in_services_block && [[ "$line" =~ ^[[:space:]]{2}([a-zA-Z0-9_-]+): ]]; then
-            service="${BASH_REMATCH[1]}"
-            {
-              if [ "$service" == "${{ steps.setup.outputs.host }}" ]; then
-                echo "  $service:"
-                echo "    networks:"
-                echo "      - default"
-                echo "      - ${{ steps.setup.outputs.network }}"
-                echo "    labels:"
-                echo "      - \"traefik.enable=true\""
-                echo "      - \"traefik.http.routers.$service.rule=Host(\`${{ steps.setup.outputs.domain }}\`)\""
-                echo "      - \"traefik.http.routers.$service.entrypoints=websecure\""
-                echo "      - \"traefik.http.routers.$service.tls.certresolver=letsencrypt\""
-                echo "      - \"traefik.http.services.$service.loadbalancer.server.port=${{ steps.setup.outputs.port }}\""
-                echo "      - \"traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https\""
-                echo "      - \"traefik.http.routers.$service.middlewares=redirect-to-https\""
-                echo "      - \"traefik.docker.network=${{ steps.setup.outputs.network }}\""
-              else
-                echo "  $service:"
-                echo "    networks:"
-                echo "      - default"
+            actual_service="${BASH_REMATCH[1]}"
+            target_found=false
+            while read -r target; do
+              # Skip empty lines
+              [[ -z "$target" ]] && continue
+              IFS=':' read -r TARGET_DOMAIN TARGET_SERVICE TARGET_PORT <<< "$target"
+
+              # SET TARGET DOMAIN NAME
+              if [ "${{ env.BRANCH_NAME }}" != "master" ]; then
+                TARGET_DOMAIN=$TARGET_DOMAIN.dev
               fi
-            } >> "$OUTPUT_FILE"
+              TARGET_DOMAIN=$TARGET_DOMAIN.${{ inputs.domain }}
+
+              if [[ "$actual_service" == "$TARGET_SERVICE" ]]; then
+                target_found=true
+                {
+                  echo "  $actual_service:"
+                  echo "    networks:"
+                  echo "      - default"
+                  echo "      - ${{ steps.setup.outputs.network }}"
+                  echo "    labels:"
+                  echo "      - \"traefik.enable=true\""
+                  echo "      - \"traefik.http.routers.$actual_service.rule=Host(\`$TARGET_DOMAIN\`)\""
+                  echo "      - \"traefik.http.routers.$actual_service.entrypoints=websecure\""
+                  echo "      - \"traefik.http.routers.$actual_service.tls.certresolver=letsencrypt\""
+                  echo "      - \"traefik.http.services.$actual_service.loadbalancer.server.port=$TARGET_PORT\""
+                  echo "      - \"traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https\""
+                  echo "      - \"traefik.http.routers.$actual_service.middlewares=redirect-to-https\""
+                  echo "      - \"traefik.docker.network=${{ steps.setup.outputs.network }}\""
+                } >> "$OUTPUT_FILE"
+                break
+              fi
+            done <<< "$TARGETS"
+            if ! $target_found; then
+              {
+                echo "  $actual_service:"
+                echo "    networks:"
+                echo "      - default"
+              } >> "$OUTPUT_FILE"
+            fi
           fi
         done < "$INPUT_FILE"
         
@@ -235,7 +300,6 @@ runs:
         echo ""
         
         NETWORK_NAME=${{ steps.setup.outputs.network }}
-        DOMAIN_NAME=${{ steps.setup.outputs.domain }}
         
         ssh -o StrictHostKeyChecking=no sshserver << EOF
           # Check if the Docker network exists; if not, create it
